[package]
name = "sightread"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"
resolver = "2"

[dependencies]
# spectrum-analyzer = "0.5.2"
wee_alloc = "0.4.5"
# rustfft = "6.0.0"

[lib]
crate-type = ["cdylib"]